language: python

python: 3.4

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8

install:
  - travis_retry pip install tox

script:
  - make test

notifications:
  irc: "irc.freenode.org#tvrenamr"
